### ISSUE TITLE
Problème de déploiement sur avent.data.gouv

### ISSUE THREAD

**Issue by pachevalier** [etalab/calendrier-lavent#11]

**Comment by schignard** [comment]
Il y a une 404 ici: https://avent.data.gouv.fr/calendrier-lavent/2017/01.html

**Comment by Skeith918** [comment]
@pachevalier problème réglé, lié à un soucis de pull sur le serveur dédié avent.data.gouv.fr
@schignard merci d'ouvrir une issue dédié, le problème ne concerne que la version https://etalab.github.io/calendrier-lavent
