### ISSUE TITLE
Problème d'affichage

### ISSUE THREAD

**Issue by pachevalier** [etalab/calendrier-lavent#26]
Sur la home, l'affichage est décalé. 

- Le premier article (prénoms) a été publié sur la case 30 qui ne devrait pas exister. 
- Le second article (data.gouv) a été publié le 1er décembre au lieu du 2 décembre
- Le troisième article (RPLS) a été publié sur le 2 décembre au lieu du 3 décembre
- Le quatrième article a été publié sur le 3 décembre au lieu du 4.

![scrrenshot](https://user-images.githubusercontent.com/3227753/33611181-c15ccf36-d9cd-11e7-8acc-900a72e9637f.png)

Du coup, le 5ème article apparaît sur la case du 4 décembre et la case 5 apparaît juste en bas à droite.

**Comment by thom4parisot** [comment]
On dirait que ça vient de la configuration des dates…

Sur ma machine / etalab.github.io/calendrier-lavent/ :

<img width="623" alt="screen shot 2017-12-05 at 15 40 25" src="https://user-images.githubusercontent.com/138627/33615680-a6df681c-d9d2-11e7-8e03-36db87468f30.png">


Sur avent.data.gouv.fr (on voit que l'horloge est décalée de 2h) :

<img width="607" alt="screen shot 2017-12-05 at 15 38 16" src="https://user-images.githubusercontent.com/138627/33615636-8a4768f8-d9d2-11e7-9f2e-8fd160b676d9.png">

**Comment by thom4parisot** [comment]
C'est rectifié avec #27 :-)

Merci pour ton œil affuté @pachevalier !
